import Storage from "./bookModules/storage.js";
import Book from "./bookModules/book.js";
import Library from "./bookModules/library.js";

const mainLibraryStorage = new Storage("mainLibrary")

const mainLibrary = new Library()

const bookArray = [new Book("A Journey to the Grove", "satisfaction", "Orchids and Narcotics"), new Book("A Light in the Inkwell", "revelation", "Inks of Revelation"), new Book("The Locksmith's Dream: A Light Throught The Keyhole", "revelation", "Lockworks and Clockworks"), new Book("The Locksmith's Dream: Portions and Proportions", "confounding parable", "Lockworks and Clockworks"), new Book("The Locksmith's Dream: Stolen Reflections", "revelation", "Watchman's Paradoxes"), new Book("The Locksmith's Dream: Trespasses", "impulse", "Edicts Liminal"), new Book("A Pale Lady and a Prince of Wine", "salt", "Sea Stories"), new Book("A Second Glory", "hindsight", "Snow Stories"), new Book("A Seventh Voice", "confounding parable", "Preliminal Meter"), new Book("A Shape In Smoke", "revelation", "Pyroglyphics"), new Book("A true and complete accounting of the asclepian mysteries of the roots of the house", "impulse", "Weaving and Knotworking"), new Book("A True History of Valentine Dewulf", "fear", "Furs and Feathers"), new Book("Advice on Containment", "regret", "Glassblowing & Vessel Crafting"), new Book("Against the Sisterhood of the Knot and the Foulness of their Depraved Customs", "intuition", "Sky Stories"), new Book("Against Vitruvius", "pattern", "Lockworks and Clockworks"), new Book("An Exorcist's Field Manual", "contradiction", "Edicts Martial"), new Book("An Impertinent Vitulation", "satisfaction", "Leaves and Thorns"), new Book("An Introduction to Histories", "hindsight", "Snow Stories"), new Book("Annals of St Brandan's", "regret", "Inks of Containment"), new Book("As the Sun His Course", "contradiction", "Sickle and Eclipse"), new Book("Ascite Supplications", "impulse", "Stone Stories"), new Book("Bancroft Diaries", "foresight", "Pyroglyphics"), new Book("Black Nephrite", "fear", "Wolf Stories"), new Book("By Their Marks Shall Ye Know Them", "pattern", "Surgeries and Exsanguinations"), new Book("Calcite Supplications", "satisfaction", "Tridesma Hiera"), new Book("Cardea's Delight", "pattern", "The Great Signs and the Great Scars"), new Book("Chione at Abydos", "regret", "Snow Stories"), new Book("Collected Hush House Lectures", "intuition", "Sickle and Eclipse"), new Book("Colours in the Liver", "revelation", "Resurgences and Emergences"), new Book("Commandments For the Preservation of All that Exists", "satisfaction", "Stitching and Binding"), new Book("Cucurbit Prisoner Records 1927", "impulse", "Insects and Nectars"), new Book("Cucurbit Prisoner Records 1928", "impulse", "Hill and Hollow"), new Book("Damascene Traditions of the House of Lethe", "impulse", "Sacra Limiae"), new Book("De Bellis Murorum", "contradiction", "Disciplines of the Scar"), new Book("De Horis Book 1", "impulse", "Rites of the Roots"), new Book("De Horis Book 2", "foresight", "Disciplines of the Hammer"), new Book("De Horis Book 3", "contradiction", "Disciplines of the Scar"), new Book("De Ratio Quercuum", "Earth-sign", "Rites of the Roots")]

bookArray.forEach(book => mainLibrary.addBook(book))

export default mainLibrary