const recipeFactory = (type, name, aspect, ingredients, skill, workstation, result, notes) => {
    return { type, name, aspect, ingredients, skill, workstation, result, notes }
}

//Beverages
const tisane = recipeFactory("Beverages", "Witching Tisane", "Grail", "N/A", ["Orchids and Narcotics", "Leaves and Thorns", "Desires and Dissolutions", "The Great Signs and the Great Scars", "Sea Stories"], "Any", ["Heart", "2 Grail"])
const cordials = recipeFactory("Beverages", "Thirza's Cordials", "Nectar", "N/A", ["Herbs and Infusions", "Coil and Chasm", "Spices and Savours", "Stone Stories",
"Orchids and Narcotics"], "Any", ["2 Moth", "2 Grail"])
const eigengrau = recipeFactory("Beverages", "Eigengrau", "Winter", "N/A", ["Auroral Contemplations", "Sights and Sensations",  "Quenchings and Quellings", "Inks of Containment", "Maggephene Mysteries", "Pearl and Tide"], "Any", ["Winter", "Moon"])
const rubywise = recipeFactory("Beverages", "Rubywise Ruin", "Grail", "Flower", ["Desires and Dissolutions", "Orchids and Narcotics", "Applebright Euphonies", "Leaves and Thorns"], ["Glassware", "Malachite", "Knot", "Calicite", "Dispensary", "Kitchens"], ["2 Rose", "2 Moth", "2 Nectar", "2 Heart", "4 Grail"])
const solomon = recipeFactory("Beverages", "Solomon's Preparation", "Winter", "Flower", ["Maggephene Mysteries", "Edicts Inviolable", "Sights and Sensations", "Ragged Crossroads", "Quenchings and Quellings", "Inks of Containment"], ["Glassware", "Malachite", "Knot", "Calicite", "Dispensary", "Kitchens"], ["Moth", "Moon", "4 Winter"])
const leathy = recipeFactory("Beverages", "Leathy", "Nectar", "N/A", ["Rites of the Roots", "Herbs and Infusions", "Insects and Nectars", "Orchids and Narcotics", "Inks of Containment"], "Any", ["2 Scale", "2 Nectar", "2 Grail", "4 Moth"])
const ascite = recipeFactory("Beverages", "Sacrament Ascite", "Knock", "Glassfinger Toxin", ["Serpents and Venoms", "Glassblowing and Vesselcrafting", "Door and Wall", "Solutions and Separations", "Horns and Ivories", "Edicts Liminal", "Stone Stories(with any liquid)"], ["Kitchen Gaol", "Glassware"], ["6 Knock"])
const calcite = recipeFactory("Beverages", "Sacrament Calcite", "Grail", "Rubywise Ruin", ["Orchids and Narcotics", "Applebright Euphonies", "Leaves and Thorns", "Sea Stories", "Tridesma Hiera"], ["Kitchens", "Glassware", "Chrysalis", "Dispensary", "Nocturnary"], "6 Grail")
const malachite = recipeFactory("Beverages", "Sacrament Malachite", "Nectar", "Pyrus Auricalcinus", ["Drums and Dances", "Spices and Savours", "Leaves and Thorns", "Rites of the Roots", "Herbs and Infusions", "Coil and Chasm"], "Kitchens", "6 Nectar")
const serpent = recipeFactory("Beverages", "Serpent-Milk", "Edge", "Perinculate", ["Sharps", "Meniscate Reflections", "Disciplines of the Scar", "Serpents and Venoms", "Sickle and Eclipse"], ["Chrysalis", "Foundry"], ["2 Knock", "3 Scale", "6 Edge"])
const skinshuck = recipeFactory("Beverages", "Skinshuck Mead", "Moth", "Honey", ["Solutions and Separations", "Edicts Liminal", "Sacra Limiae", "Rites of the Roots", "Resurgences and Emergences(cuckoo honey)", "Transformations and Liberations(cuckoo honey)", "Insects and Nectar(cuckoo honey)"], "Kitchens", ["2 Scale", "2 Nectar", "2 Heart", "6 Moth"])

//Inks
const yewgall = recipeFactory("Inks", "Yewgall Ink", "Nectar", "N/A", ["Rites of the Roots", "Insects and Nectars", "Leaves and Thorns", "Putrefactions and Calcinations"], "Any", ["2 Nectar"])
const perhibiate = recipeFactory("Inks", "Perhibiate", "Heart", "N/A", ["Stitching and Binding", "Weaving and Knotworking", "Inks of Power"], "Any", ["Winter", "2 Lantern", "2 Scale", "2 Heart"])
const stargall = recipeFactory("Inks", "Stargall Ink", "Sky", "N/A", ["Inks of Power", "Inks of Revelation", "Inks of Containment"], "Any", "2 Sky")
const catwink = recipeFactory("Inks", "Catwink", "Moon", "N/A", ["Inks of Containment", "Sickle and Eclipse", "Sand Stories", "Putrefactions and Calcinations", "Edicts Inviolable"], "Any", ["2 Moon", "2 Scale"])
const perinculate = recipeFactory("Inks", "Perinculate", "Edge", "Leaf", ["Sickle and Eclipse", "Inks of Power", "Edicts Martial", "Disciplines of the Scar", "Putrefactions and Calcinations"], ["Kitchens", "Glassware"], ["4 Edge", "4 Scale"])
const asimel = recipeFactory("Inks", "Asimel", "Moon", "Liquid", ["Inks of Revelation", "Putrefactions and Calcinations", "Sea Stories", "Ouranoscopy", "Pearl and Tide"], ["Chrysalis", "Dispensary", "Foundry", "Nocturnary"],["3 Knock", "5 Moon"])
const houndsgall = recipeFactory("Inks", "Houndsgall", "Scale", "Living Relic", ["Inks of Containment", "Path and Pilgrim", "Horns and Ivories", "Pentiments and Precursors"], ["Rowenarium", "Ascite", "Malachite", "Knot", "Calicite", "Catacombs", "Januarius", "Madrugad", "Watchman", "Solar", "Spire", "Tower-top"], ["2 Heart", "5 Scale"])
const ashartine = recipeFactory("Inks", "Ashartine", "Lantern", "Ichor Vitreous", ["Pyroglyphics", "Watchman's Paradoxes", "Glaziery and Lightsmithing", "Anbary and Lapidary", "Glassblowing and Vesselcrafting"], ["Glassware"], ["2 Sky", "6 Lantern"])
const marakat = recipeFactory("Inks", "Marakat", "Nectar", "Leathy", ["Insects and Nectars", "Inks of Power", "Tridesma Hiera"], ["Chrysalis", "Dispensary", "Kitchens", "Foundry", "Nocturnary", "Cage", "Calicite"], ["7 Grail", "7 Knock", "7 Nectar"])
const nillycant = recipeFactory("Inks", "Nillycant", "Winter", ["Solomon's Preparation", "Glassfinger Toxin(with Ragged Crossroads)"], ["Inks of Containment", "Sights and Sensations", "Ragged Crossroads"], ["Hearth: Hall of Voices", "Calicite", "Glassware", "Dispensary", "Foundry", "Nocturnary"], ["7 Scale", "7 Winter", "7 Edge"])
const orpiment = recipeFactory("Inks", "Orpiment Exultant", "Forge", "Iotic Essence", ["Transformations and Liberations", "Inks of Power", "Anbary and Lapidary"], ["Foundry", "Glassware", "Condignator", "Oubliette Containment", "Kitchen Gaol"], ["7 Heart", "7 Sky", "7 Forge"])
const porphyrine = recipeFactory("Inks", "Porphyrine", "Rose", "Ichor Auroral", ["Auroral Contemplations", "Inks of Revelation", "Inks of Power", "Pearl and Tide", "Sand Stories"], ["Glassware", "Rowenarium", "Loggia"], ["7 Knock", "7 Moon", "7 Rose"])
const uzult = recipeFactory("Inks", "Uzult", "Lantern", "Xanthotic Essence", ["Inks of Revelation", "Sacra Solis Invicti", "Watchman's Paradoxes", "Glaziery and Lightsmithing", "Anbary and Lapidary"], ["Glassware", "Dispensary", "Foundry"], ["7 Lantern", "7 Moth", "7 Sky"])

//Memories
const thunderskin = recipeFactory("Memories", "Thunderskin's Paean", "Heart", "10 Heart", ["Drums and Dances", "Strings and Songs"], "Instrument", ["Scale", "Grail", "Heart 4"], "Evolve via Preservation")
const nameday = recipeFactory("Memories", "Nameday Riddle", "Moth", ["10 Moth", "Memory"], ["Sacra Limiae", "Edicts Liminal", "Solutions and Separations", "Rites of the Roots", "Weaving and Knotworking"], "Any", ["2 Knock", "3 Moth"])
const moment = recipeFactory("Memories", "Old Moment", "Scale", "10 Lantern or 10 Scale", ["Disciplines of the Scar", "Wolf Stories", "Coil and Chasm", "Horns and Ivories", "Path and Pilgrim"], "Any", ["2 Moth", "2 Lantern", "4 Scale"], ["Can be obtained from Living Relic and Year-Tally", "Evolve via Preservation"])
const torgue = recipeFactory("Memories", "Torgue's Cleansing", "Edge", "5 Edge", ["Auroral Contemplations", "Disciplines of the Scar", "Meniscate Reflections", "Purifications and Exaltations", "Sharps"], "Any", "2 Edge")
const winning = recipeFactory("Memories", "Winning Move", "Edge", ["10 Edge", "Memory"], ["Sharps", "Disciplines of the Hammer", "Ragged Crossroads", "Auroral Contemplations"], "Any", "3 Edge", "Evolve via Illumination")
const ascendant = recipeFactory("Memories", "Ascendant Harmony", "Sky", "10 Sky", ["Applebright Euphonies", "Bells and Brazieries", "Furs and Feathers", "Purifications and Exaltations", "Sky Stories", "Strings and Songs"], "Instrument", ["2 Lantern", "4 Sky"], "Evolve via Birdsong")
const curious = recipeFactory("Memories", "Curious Hunch", "Knock", ["10 Knock", "Memory"], ["Preliminal Meter", "The Great Signs and the Great Scars"], "Any", ["3 Moth", "3 Lantern", "3 Heart", "4 Knock"], ["Evolve via Nyctodromy", "Sea's Edge in numa", "Persistent"])
const didumos = recipeFactory("Memories", "Didumos", "Sky", ["15 Sky", "Ascendant Harmony"], ["Ouranoscopy", "Sights and Sensations", "Bells and Brazieries", "Applebright Euphonies", "Sacra Limiae"], "Any", ["3 Winter", "3 Knock", "3 Lantern", "Sky 6"], ["Evolve via Horomachistry", "Evolve via Hushery", "Persistent"])
const earth = recipeFactory("Memories", "Earth-Sign", "Nectar", "N/A", ["De Ratio Quercuum", "Rapt in the King"], "Any", ["2 Scale", "2 Nectar"], ["Evolve via Skolekosophy", "Walk on the moor in numa", "Persistent", "Viper or Spider"])
const quake = recipeFactory("Memories", "Earthquake-name", "Scale", ["15 Scale","15 Lantern(Disciplines of the Scar)", "Old Moment"], ["Coil and Chasm", "Hill and Hollow", "Stone Stories", "Wolf Stories", "Disciplines of the Scar"], "Any", ["3 Forge", "6 Scale"], "Persistent")
const enduring = recipeFactory("Memories", "Eduring Reflection", "Rose", ["10 Rose", "Memory"], ["Pearl and Tide", "Preliminal Meter", "Path and Pilgrim"], "Any", ["1 Heart", "1 Knock", "3 Rose"], ["Evolve via Nyctodromy", "Persistent", "Moor or Sea Caves in numa"])
const forbidden = recipeFactory("Memories", "Forbidden Epic", "Edge", ["15 Moon", "Confounding Parable"], "Edicts Martial", "Any", ["4 Moon", "4 Rose", "6 Edge"], ["Evolve via Horomachistry", "Evolve via Birdsong"])
const hive = recipeFactory("Memories", "Hive's Lament", "Nectar", "10 Nectar", "Drums and Dances", "Instrument", ["2 Moth", "2 Winter", "4 Nectar"], ["Evolve via Bosk", "Persistent"])
const horizon = recipeFactory("Memories", "Horizon-Sight", "Rose", ["15 Rose", "Enduring Reflection"], ["Path and Pilgrim", "Preliminal Meter", "Sand Stories", "Sky Stories"], "Any", "Rose 4", ["Evolve via Hushery", "Persistent", "Stymphling", "Gull Colony in numa"])
const invincible = recipeFactory("Memories", "Invincible Audacity", "Edge", ["15 Edge", "Winning Move"], ["Auroral Contemplations", "Disciplines of the Hammer", "Edicts Martial"], "Any", ["3 Forge", "3 Lantern", "6 Edge"], ["Evolve via Illumination", "Evolve via Ithastry", "Persistent"])
const occult = recipeFactory("Memories", "Occult Scrap", "Rose", "N/A", "Yellowing Newspaper", "Any", ["2 Knock", "2 Moth", "2 Rose"], "Persistent")
const wound = recipeFactory("Memories", "Old Wound", "Moon", "5 Moon", "Edicts Martial", "Any", ["1 Edge", "2 Moon", "3 Winter"], "Persistent")
const wind = recipeFactory("Memories", "Wind-in-Waiting", "Sky", ["15 Sky", "Mazarine Fife"], ["Strings and Songs", "Sky Stories", "Sacra Solis Invicti","Furs and Feathers"], ["Gullscry", "Hermit", "Ambrose", "Reading Room", "Pale", "Telescope"], ["3 Moth", "3 Grail", "3 Scale", "6 Sky"], ["Evolve via Bosk", "Evolve via Birdsong", "Persistent"])
const wormwood = recipeFactory("Memories", "Womrwood Dream", "Winter", ["10 Moon(Edicts Martial)", "Memory(Edicts Martial)","15 Moon", "Stymphling"], ["Edicts Martial", "Edicts Inviolable", "Rhyme and Remembrance", "Snow Stories", "Wolf Stories", "Sickle and Eclipse"], "Any", ["3 Edge", "6 Moon", "6 Winter"], ["Evolve via Skolekosophy", "Evolve via Nyctodromy", "Persistent"])

// Tool
const mazarine = recipeFactory("Devices", "Mazarine Fife", "Sky", ["10 Sky", "Wood"], ["Ouranoscopy", "Sacra Limiae", "Sacra Solis Invicti"], ["Gullscry", "Hermit", "Solar Altar"], "3 Sky", "Instrument")
const chronsichord = recipeFactory("Devices", "Chronsichord", "Knock", ["15 Knock", "Gervinite", "15 Sky(Lockworks)", "Silver Wire(Lockworks)"], ["Lockworks and Clockworks", "Preliminal Meter", "Glassblowing and Vesselcrafting", "The Great Signs and the Great Scars", "Glaziery and Lightsmithing"], "Any", ["Forge", "3 Winter", "6 Sky", "6 Knock"])
const mommet = recipeFactory("Devices", "Pale Mommet", "Grail", ["10 Grail", "Fabric"], ["Pentiments and Precursors", "Resurgences and Emergences", "Sea Stories", "The Great Signs and the Great Scars", "Tridesma Hiera"], "Loom in Servants' Hall", ["2 Heart", "2 Moth", "4 Grail"])
const flushed = recipeFactory("Devices", "Flushed Mommet", "Grail", ["15 Grail", "Pale Mommet"], ["Pentiments and Precursors", "The Great Signs and the Great Scars", "Desires and Dissolutions", "Resurgences and Emergences", "Furs and Feathers"], "Any", ["3 Moth", "3 Heart", "6 Grail"])
const dearday = recipeFactory("Devices", "Dearday Lens", "Lantern", "5 Lantern or 5 Sky(Glassblowing and Glaziery)", ["Glaziery and Lightsmithing", "Pyroglyphics", "Disciplines of the Scar", "Glassblowing and Vesselcrafting"], "Mainly Telescope", ["Forge", "Edge", "2 Sky", "2 Lantern"])

//Material 
const gervinite = recipeFactory("Materials", "Gervinite", "Knock", ["10 Knock", "Glass", "10 Sky(Glaziery)", "Metal(Glaziery)"], ["Lockworks and Clockworks", "Glaziery and Lightsmithing"], ["Dispensary(Lockworks)", "Any that accepts metal"], ["2 Rose", "4 Knock"], ["Found in Our Lady Beneath", "In weighty bedside candleholder"])


const recipeList = [tisane, cordials, eigengrau, rubywise, yewgall, solomon, leathy, ascite, calcite, malachite, serpent, skinshuck, perhibiate, stargall, catwink, perinculate, asimel, houndsgall, ashartine, marakat, nillycant, orpiment, porphyrine, uzult, thunderskin, nameday, forbidden, moment, torgue, winning, ascendant, curious, didumos, earth, quake, enduring, hive, horizon, invincible, occult, wound, wind, wormwood, mazarine, chronsichord, mommet, flushed, dearday]
export default recipeList