const skillFactory = (name, principles, wisdoms, attunables) => {
    return { name, principles, wisdoms, attunables }
}

const anbary = skillFactory("Anbary and Lapidary", ["Sky", "Forge"], ["Horomachistry", "Ithastry"], ["Fet", "Phost"])
const applebright = skillFactory("Applebright Euphonies", ["Sky", "Grail"], ["Bosk", "Illumination"], ["Ereb", "Mettle"])
const auroral = skillFactory("Auroral Contemplations", ["Lantern", "Edge"], ["Illumination", "Nyctodromy"], ["Phost", "Fet"])
const bells = skillFactory("Bells and Brazieries", ["Forge", "Sky"], ["Horomachistry", "Ithastry"], ["Mettle", "Wist"])
const coil = skillFactory("Coil and Chasm", ["Scale", "Nectar"], ["Nyctodromy", "Skolekosophy"], ["Shapt", "Ereb"])
const desires = skillFactory("Desires and Dissolutions", ["Grail", "Moon"], ["Bosk", "Horomachistry"], ["Ereb", "Mettle"])
const hammer = skillFactory("Disciplines of the Hammer", ["Edge", "Forge"], ["Illumination", "Nyctodromy"], ["Mettle", "Shapt"])
const scar = skillFactory("Disciplines of the Scar", ["Edge", "Lantern"], ["Hushery", "Illumination"], ["Trist", "Phost"])
const door = skillFactory("Door and Wall", ["Knock", "Forge"], ["Horomachistry", "Nyctodromy"], ["Fet", "Shapt"])
const drums = skillFactory("Drums and Dances", ["Heart", "Nectar"], ["Bosk", "Horomachistry"], ["Health", "Mettle"])
const inviolable = skillFactory("Edicts Inviolable", ["Heart", "Moon"], ["Horomachistry", "Preservation"], ["Mettle", "Chor"])
const liminal = skillFactory("Edicts Liminal", ["Moth", "Knock"], ["Nyctodromy", "Skolekosophy"], ["Fet", "Ereb"])
const martial = skillFactory("Edicts Martial", ["Moon", "Edge"], ["Horomachistry", "Illumination"], ["Mettle", "Phost"])
const fur = skillFactory("Furs and Feathers", ["Sky", "Scale"], ["Bosk", "Nyctodromy"], ["Health", "Fet"])
const glass = skillFactory("Glassblowing and Vesselcrafting", ["Knock", "Sky"], ["Hushery", "Ithastry"], ["Wist", "Phost"])
const glaz = skillFactory("Glaziery and Lightsmithing", ["Lantern", "Sky"], ["Illumination", "Ithastry"], ["Mettle", "Phost"])
const herbs = skillFactory("Herbs and Infusions", ["Heart", "Nectar"], ["Bosk", "Preservation"], ["Ereb", "Health"])
const hill = skillFactory("Hill and Hollow", ["Moon", "Scale"], ["Birdsong", "Preservation"], ["Chor", "Health"])
const horns = skillFactory("Horns and Ivories", ["Scale", "Knock"], ["Bosk", "Skolekosophy"], ["Ereb", "Shapt"])
const contain = skillFactory("Inks of Containment", ["Winter", "Moon"], ["Horomachistry", "Preservation"], ["Mettle", "Health"])
const power = skillFactory("Inks of Power", ["Rose", "Scale"], ["Horomachistry", "Hushery"], ["Mettle", "Trist"])
const revelation = skillFactory("Inks of Revelation", ["Lantern", "Moth"], ["Hushery", "Ithastry"], ["Wist", "Phost"])
const insects = skillFactory("Insects and Nectars", ["Nectar", "Moon"], ["Bosk", "Nyctodromy"], ["Ereb", "Fet"])
const leaves = skillFactory("Leaves and Thorns", ["Nectar", "Grail"], ["Birdsong", "Bosk"], ["Chor", "Health"])
const lock = skillFactory("Lockworks and Clockworks", ["Knock","Sky"], ["Ithastry","Skolekosophy"], ["Wist", "Shapt"])
const magg = skillFactory("Maggephene Mysteries", ["Moon", "Heart"], ["Hushery", "Preservation"], ["Trist", "Health"])
const menis = skillFactory("Meniscate Reflections", ["Forge", "Edge"], ["Illumination", "Preservation"], ["Phost", "Health"])
const orchid = skillFactory("Orchids and Narcotics", ["Grail", "Nectar"], ["Bosk", "Skolekosophy"], ["Ereb", "Shapt"])
const ouran = skillFactory("Ouranoscopy", ["Sky", "Moon"], ["Horomachistry", "Hushery"], ["Fet", "Trist"])
const path = skillFactory("Path and Pilgrim", ["Rose", "Scale"], ["Birdsong", "Nyctodromy"], ["Chor", "Fet"])
const pearl = skillFactory("Pearl and Tide", ["Rose", "Moon"], ["Bosk", "Nyctodromy"], ["Health", "Fet"])
const penti = skillFactory("Pentiments and Precursors", ["Scale", "Grail"], ["Birdsong", "Skolekosophy"], ["Chor", "Ereb"])
const prelim = skillFactory("Preliminal Meter", ["Knock", "Rose"], ["Illumination", "Ithastry"], ["Phost", "Wist"])
const puri = skillFactory("Purifications and Exaltations", ["Sky", "Lantern"], ["Illumination", "Ithastry"], ["Mettle", "Phost"])
const putre = skillFactory("Putrefactions and Calcinations", ["Winter", "Moon"], ["Ithastry", "Skolekosophy"], ["Wist", "Ereb"])
const pyro = skillFactory("Pyroglyphics", ["Forge", "Lantern"], ["Illumination", "Ithastry"], ["Mettle", "Wist"])
const quench = skillFactory("Quenchings and Quellings", ["Winter", "Heart"], ["Hushery", "Preservation"], ["Trist", "Health"])
const ragged = skillFactory("Ragged Crossroads", ["Edge", "Winter"], ["Illumination", "Skolekosophy"], ["Phost", "Shapt"])
const resur = skillFactory("Resurgences and Emergences", ["Moth", "Grail"], ["Bosk", "Preservation"], ["Health", "Chor"])
const rhyme = skillFactory("Rhyme and Remembrances", ["Winter", "Moon"], ["Birdsong", "Skolekosophy"], ["Trist", "Ereb"])
const rites = skillFactory("Rites of the Roots", ["Nectar", "Moth"], ["Bosk", "Preservation"], ["Ereb", "Health"])
const sacra = skillFactory("Sacra LImiae", ["Moth", "Sky"], ["Horomachistry", "Hushery"], ["Mettle", "Trist"])
const solis = skillFactory("Sacra Solis Invicti", ["Lantern", "Sky"], ["Horomachistry", "Illumination"], ["Fet", "Phost"])
const sand = skillFactory("Sand Stories", ["Rose", "Moon"], ["Birdsong", "Skolekosophy"], ["Trist", "Shapt"])
const sea = skillFactory("Sea Stories", ["Moon", "Grail"], ["Birdsong", "Nyctodromy"], ["Chor", "Shapt"])
const serp = skillFactory("Serpents and Venoms", ["Scale", "Moon"], ["Hushery", "Skolekosophy"], ["Trist", "Shapt"])
const sharps = skillFactory("Sharps", ["Edge", "Moon"], ["Hushery", "Skolekosophy"], ["Wist", "Shapt"])
const sickle = skillFactory("Sickle and Eclipse", ["Edge", "Moon"], ["Nyctodromy", "Preservation"], ["Shapt", "Chor"])
const sights = skillFactory("Sights and Sensations", ["Sky", "Winter"], ["Hushery", "Nyctodromy"], ["Wist", "Fet"])
const sky = skillFactory("Sky Stories", ["Sky", "Rose"], ["Birdsong", "Horomachistry"], ["Trist", "Fet"])
const snow = skillFactory("Snow Stories", ["Winter", "Moon"], ["Birdsong", "Hushery"], ["Trist", "Wist"])
const solu = skillFactory("Solutions and Separations", ["Moth", "Knock"], ["Ithastry", "Skolekosophy"], ["Wist", "Shapt"])
const spices = skillFactory("Spices and Savours", ["Nectar", "Forge"], ["Bosk", "Ithastry"], ["Health", "Ereb"])
const stitch = skillFactory("Stitching and Binding", ["Sky", "Heart"], ["Ithastry", "Preservation"], ["Wist", "Chor"])
const stone = skillFactory("Stone Stories", ["Scale", "Nectar"], ["Birdsong", "Preservation"], ["Trist", "Chor"])
const strings = skillFactory("Strings and Songs", ["Sky", "Heart"], ["Birdsong", "Nyctodromy"], ["Chor", "Shapt"])
const surgeries = skillFactory("Surgeries and Exsanguinations", ["Heart", "Knock"], ["Hushery", "Preservation"], ["Wist", "Chor"])
const signs = skillFactory("The Great Signs and the Great Scars", ["Grail", "Knock"], ["Horomachistry", "Hushery"], ["Fet", "Trist"])
const trans = skillFactory("Transformations and Liberations", ["Forge", "Moth"], ["Illumination", "Ithastry"], ["Mettle", "Phost"])
const trid = skillFactory("Tridesma Hiera", ["Moon", "Grail"], ["Bosk", "Preservation"], ["Ereb", "Health"])
const watch = skillFactory("Watchman's Paradoxes", ["Lantern", "Sky"], ["Illumination", "Nyctodromy"], ["Phost", "Fet"])
const weaving = skillFactory("Weaving and Knotworking", ["Heart", "Moth"], ["Birdsong", "Bosk"], ["Chor", "Health"])
const wolf = skillFactory("Wolf Stories", ["Moon", "Scale"], ["Birdsong", "Skolekosophy"], ["Trist" ,"Ereb"])

const crack = skillFactory("Cracktrack", ["Nectar", "Scale"], ["Illumination", "Preservation"], ["Phost", "Chor"])
const man = skillFactory("Deep Mandaic", ["Forge", "Lantern"], ["Horomachistry", "Ithastry"], ["Mettle", "Phost"])
const eri = skillFactory("Ericapaean", ["Lantern", "Winter"], ["Hushery", "Illumination"], ["Trist", "Phost"])
const fucine = skillFactory("Fucine", ["Heart", "Knock"], ["Hushery", "Ithastry"], ["Trist", "Wist"])
const hyksos = skillFactory("Hyksos", ["Grail", "Edge"], ["Nyctodromy", "Skolekosophy"], ["Shapt", "Ereb"])
const kern = skillFactory("Kernewek Henavek", ["Scale", "Forge"], ["Bosk", "Ithastry"], ["Health", "Wist"])
const kill = skillFactory("Killasimi", ["Winter", "Moon"], ["Bosk", "Skolekosophy"], ["Health", "Ereb"])
const ram = skillFactory("Ramsund", ["Moth", "Sky"], ["Birdsong", "Preservation"], ["Trist", "Chor"])
const sab = skillFactory("Sabazine", ["Moth", "Lantern"], ["Birdsong", "Horomachistry"], ["Trist", "Fet"])
const vak = skillFactory("Vak", ["Knock", "Rose"], ["Birdsong", "Nyctodromy"], ["Chor", "Fet"])



const skillList = [anbary,applebright, auroral, bells, coil, crack, man, desires, door, hammer, scar, drums,  inviolable, liminal, martial, eri, fucine, fur, glass, glaz, herbs, hill, horns, hyksos, contain, power, revelation, insects,kern, kill, ram,  leaves, lock, magg, menis, orchid, ouran, path, pearl, penti, prelim, puri, putre, pyro, quench, ragged,resur, rhyme, rites, sab, sacra, solis, sand, sea, serp, sharps, sickle, sights, sky, snow, solu, spices, stitch, stone, strings, surgeries, signs, trans, trid, vak, watch, weaving, wolf]

export default skillList